/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package datakelas;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.MessageFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class home extends javax.swing.JFrame {

    /**
     * Creates new form home
     */
    public home(String user) {
        initComponents();
        selectData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        tfAbsen = new javax.swing.JTextField();
        tfNIS = new javax.swing.JTextField();
        tfNama = new javax.swing.JTextField();
        tfTempat = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        dcTanggal = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        tfAlamat = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbData = new javax.swing.JTable();
        btnAdd = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnPrint = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 255, 153));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 36)); // NOI18N
        jLabel1.setText("DATA KELAS GLYPHXI");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(180, 0, 360, 50);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 10, 1070, 50);

        jPanel3.setBackground(new java.awt.Color(0, 255, 153));
        jPanel3.setLayout(null);
        jPanel3.add(tfAbsen);
        tfAbsen.setBounds(120, 90, 150, 30);
        jPanel3.add(tfNIS);
        tfNIS.setBounds(120, 10, 150, 30);
        jPanel3.add(tfNama);
        tfNama.setBounds(120, 50, 150, 30);

        tfTempat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTempatActionPerformed(evt);
            }
        });
        jPanel3.add(tfTempat);
        tfTempat.setBounds(120, 130, 150, 30);

        jLabel2.setText("Nama");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(30, 50, 60, 30);

        jLabel3.setText("Absen");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(30, 90, 50, 30);

        jLabel4.setText("NIS");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(30, 10, 40, 30);

        jLabel5.setText("Tempat Lahir");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(30, 130, 80, 30);

        jLabel6.setText("Tanggal Lahir");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(30, 170, 80, 30);

        jLabel7.setText("Alamat");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(30, 220, 60, 30);
        jPanel3.add(dcTanggal);
        dcTanggal.setBounds(120, 170, 150, 30);

        tfAlamat.setColumns(20);
        tfAlamat.setRows(5);
        jScrollPane1.setViewportView(tfAlamat);

        jPanel3.add(jScrollPane1);
        jScrollPane1.setBounds(120, 220, 160, 96);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(10, 70, 290, 410);

        jPanel2.setBackground(new java.awt.Color(0, 255, 153));
        jPanel2.setLayout(null);

        tbData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "NIS", "Nama", "Absen", "Tempat Lahir", "TanggaL Lahir", "Alamat"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbDataMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbData);

        jPanel2.add(jScrollPane2);
        jScrollPane2.setBounds(10, 60, 740, 180);

        btnAdd.setText("ADD");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jPanel2.add(btnAdd);
        btnAdd.setBounds(20, 20, 70, 23);

        btnDelete.setText("DELETE");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel2.add(btnDelete);
        btnDelete.setBounds(190, 20, 80, 23);

        btnPrint.setText("PRINT");
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });
        jPanel2.add(btnPrint);
        btnPrint.setBounds(350, 20, 70, 23);

        btnClear.setText("CLEAR");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        jPanel2.add(btnClear);
        btnClear.setBounds(110, 20, 70, 23);

        btnExit.setText("EXIT");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        jPanel2.add(btnExit);
        btnExit.setBounds(280, 20, 55, 23);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(310, 70, 770, 410);

        setBounds(0, 0, 1105, 524);
    }// </editor-fold>//GEN-END:initComponents

    private void tfTempatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTempatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTempatActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String tanggal = dateFormat.format(dcTanggal.getDate());

                
        if ("".equals(tfNIS.getText())||"".equals(tfNama.getText())||"".equals(tfAbsen.getText())||"".equals(tfTempat.getText())||"".equals(tanggal)||"".equals(tfAlamat.getText())){
            JOptionPane.showMessageDialog(this, "Harap Lengkapi Data", "Error", JOptionPane.WARNING_MESSAGE);
        }
        else{
         
         String SQL = "INSERT INTO tb_data(nis, nama, absen, tempat_lahir, tanggal_lahir, alamat) " + "VALUES('"+tfNIS.getText()+"','"+tfNama.getText()+"','"+tfAbsen.getText()+"','"+tfTempat.getText()+"','"+tanggal+"','"+tfAlamat.getText()+"')";
         int status = Koneksi_DB.execute(SQL);
         if (status == 1){
             JOptionPane.showMessageDialog(this, "Data Berhasil Ditambahkan", "Sukses", JOptionPane.INFORMATION_MESSAGE);
             selectData();
         }
         else{
             JOptionPane.showMessageDialog(this, "Data Gagal Ditambahkan", "Gagal", JOptionPane.WARNING_MESSAGE);
         }
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void tbDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbDataMouseClicked
        int baris = tbData.getSelectedRow();
        if(baris!= -1){
          tfNIS.setText(tbData.getValueAt(baris, 0).toString());
          tfNama.setText(tbData.getValueAt(baris, 1).toString());
          tfAbsen.setText(tbData.getValueAt(baris, 2).toString());
          tfTempat.setText(tbData.getValueAt(baris, 3).toString());
          tfAlamat.setText(tbData.getValueAt(baris, 5).toString());
          
          
          SimpleDateFormat date = new SimpleDateFormat("yyyy-MM-dd");
            Date dateFormat = null;
            try {
            dateFormat = date.parse(tbData.getValueAt(baris, 4).toString());
            } catch (ParseException ex) {
            Logger.getLogger(home.class.getName()).log(Level.SEVERE, null, ex);
            }

            dcTanggal.setDate(dateFormat);            
      } 
    }//GEN-LAST:event_tbDataMouseClicked

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
      tfNIS.setText("");
      tfNama.setText("");
      tfAbsen.setText("");
      tfTempat.setText("");
      dcTanggal.setDate(null);
      tfAlamat.setText("");
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int baris = tbData.getSelectedRow();
        if (baris != -1){
            String nis = tbData.getValueAt(baris, 0).toString();
            String SQL = "DELETE FROM tb_data WHERE nis='"+nis+"'";
            int status = Koneksi_DB.execute(SQL);
            if(status == 1){
                JOptionPane.showMessageDialog(this, "Data berhasil di hapus", "Sukses", JOptionPane.INFORMATION_MESSAGE);
                selectData();
            } else{
                JOptionPane.showMessageDialog(this, "Data Gagal dihapus", "Gagal", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Pilih Baris terlebih dahulu sebelum menghapus", "Error", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        MessageFormat header = new MessageFormat("DATA KELAS GLYPHXI");
       MessageFormat footer = new MessageFormat("Page {0,number,integer}");
       
       try {
           tbData.print(JTable.PrintMode.FIT_WIDTH, header, footer, true, null, true, null);
       } catch (java.awt.print.PrinterException e) {
           System.err.format("Cannot Print %s&n", e.getMessage());
       } 
    }//GEN-LAST:event_btnPrintActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        dispose();
    }//GEN-LAST:event_btnExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                String user = null;
                new home(user).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnPrint;
    private com.toedter.calendar.JDateChooser dcTanggal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbData;
    private javax.swing.JTextField tfAbsen;
    private javax.swing.JTextArea tfAlamat;
    private javax.swing.JTextField tfNIS;
    private javax.swing.JTextField tfNama;
    private javax.swing.JTextField tfTempat;
    // End of variables declaration//GEN-END:variables

    private void selectData() {
        String kolom[] = {"NIS","Nama","Absen","Tempat Lahir","Tanggal Lahir","Alamat"};
        DefaultTableModel dtm = new DefaultTableModel(null, kolom);
        String SQL = "SELECT * FROM tb_data";
        ResultSet rs = Koneksi_DB.executeQuery(SQL);
        try {
            while(rs.next()){
                String nis = rs.getString(1);
                String nama = rs.getString(2);
                String absen = rs.getString(3);
                String tempat_lahir = rs.getString(4);
                String tanggal_lahir = rs.getString(5);
                String alamat = rs.getString(6);
                String data[] = {nis, nama, absen, tempat_lahir, tanggal_lahir, alamat};
                dtm.addRow(data);
            }
        } catch(SQLException ex){
            Logger.getLogger(home.class.getName()).log(Level.SEVERE, null, ex);
        }
        tbData.setModel(dtm);
    }
}
